# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.6.0"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true
    d.volumes = ["/ml:/ml", "codevol:/ml/storage/code", "datavol:/ml/storage/data"]
  end
  config.ssh.port = 22
end
